name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Starting login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "logged"
    
    - name: Build Docker image
      run: |
        docker build -t armando101/docker-graphql:0.0.1 .
    
    - name: Push Docker Image
      run: |
        docker push armando101/docker-graphql:0.0.1
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
